import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import QueryProvider from '@/components/providers/QueryProvider';
import Navbar from '@/components/Navigation/Navbar';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import { Montserrat, Space_Grotesk } from 'next/font/google'


const monsterrat = Montserrat({
  subsets: ['latin'],
  weight:  ['100','200', '300']
})

const grotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['300', '400', '500']
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={`${monsterrat.className}`}>
          <QueryProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              <div className=" mx-auto px-5   selection:text-primary-accent">
                <Navbar />
                <main className="flex flex-col min-h-screen justify-center items-center space-y-12 md:py-8">
                  {children}
                </main>
              </div>
            </ThemeProvider>
          </QueryProvider>
        </body>
      </html>
    </>
  );
}